name: Reusable - Gates

on:
  workflow_call:
    inputs:
      java-distribution:
        required: true
        type: string
      java-version:
        required: true
        type: string
      sonar-project-key:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  sonar:
    name: Sonarqube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}

      - name: Sonarqube
        run: mvn clean verify sonar:sonar -Dsonar.projectKey=${{ inputs.sonar-project-key }} -Dsonar.token=${{ secrets.SONAR_TOKEN }} -Dsonar.qualitygate.wait=true -Pcoverage