name: Reusable - Java microservice

on:
  workflow_call:
    inputs:
      application-name:
        required: true
        type: string
      java-distribution:
        required: true
        type: string
      java-version:
        required: true
        type: string
      kubernetes-cluster-name:
        required: true
        type: string
      kubernetes-manifest-directory-path:
        required: true
        type: string
      kubernetes-namespace:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}

      - name: Build application
        run: mvn clean compile

      - name: Run tests
        run: mvn test --batch-mode --fail-at-end

      - name: Package application
        run: mvn package

      - name: Build Docker image
        run: |
          docker build -t vitoravanco/${{ inputs.application-name }}:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker login -u vitoravanco -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push vitoravanco/${{ inputs.application-name }}:${{ github.sha }}

  deploy:
    name: Deploy
    environment: production
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.1'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::637423281280:role/pipeline
          aws-region: us-east-1

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --name ${{ inputs.kubernetes-cluster-name }}

      - name: Deploy
        uses: Azure/k8s-deploy@v4
        with:
          namespace: ${{ inputs.kubernetes-namespace }}
          manifests: |
            ${{ inputs.kubernetes-manifest-directory-path }}
          images: vitoravanco/${{ inputs.application-name }}:${{ github.sha }}